name: "gcs"
version: "0.1.4"
usage: "repositories on Google Cloud Storage" 
description: |-
  Manage repositories on Google Cloud Storage
command: "$HELM_PLUGIN_DIR/bin/helm-gcs"
downloaders:
- command: "pull.sh"
  protocols:
  - "gs"

hooks:
  install: "cd $HELM_PLUGIN_DIR; ./install.sh"
  update: "cd $HELM_PLUGIN_DIR; ./install.sh"